### ISSUE TITLE
RestAPI resource weird behaviour with json_schema attribute

### ISSUE THREAD

**Issue by leonenkoa** [site24x7/terraform-provider-site24x7#113]
I see the error below when I try to use restapi monitor resource and taking into account that I don't use `json_schema` attribute in  my resource at all.
I noticed that restapi tests don't have proper test which include this attribute.

`
Error: json: cannot unmarshal string into Go struct field RestApiMonitor.json_schema of type map[string]interface {}
`

**Comment by jim-billy-zoho** [comment]
@leonenkoa Please check whether you have configured response_content_type = "J". Also, ensure you haven't configured JSON related attributes shown below.

https://github.com/site24x7/terraform-provider-site24x7/blob/eb2cd411396deaec2c8441cb30533776e9fd58cb/examples/rest_api_monitor_us.tf#L166-L188

**Comment by leonenkoa** [comment]
Yep, we use `response_content_type` and `match_json_path`, but I didn't find any relations in the code between these attributes and `json_schema` attribute. Can you please elaborate on this?

**Comment by jim-billy-zoho** [comment]
Hi Anton,

The attributes defined in terraform are analogous to the fields present in the webclient's REST API add monitor form. Have attached screenshots of the content check fields when the Response format is JSON, TEXT and XML for your reference. 
For example, when `response_content_type='T'` the related attributes you can configure are
- matching_keyword
- unmatching_keyword
- match_regex
- match_case

Similarly, when `response_content_type='J'` the related attributes you can configure are
- match_json_path
- match_json_path_severity
- json_schema
- json_schema_severity
- json_schema_check

Regards,
Jim Billy
![response_content_check_xml](https://user-images.githubusercontent.com/97297381/187209691-b900a3e3-89e9-48f2-8ab7-2671c0ce0004.png)
![response_content_check_json](https://user-images.githubusercontent.com/97297381/187209697-7070b7fc-56b7-4bcc-bc6c-0336d7277a02.png)
![response_content_check_text](https://user-images.githubusercontent.com/97297381/187209700-2ba4078e-3837-486f-94a3-5bca09273e7b.png)

**Comment by patrungel** [comment]
Can this be re-opened please?

I encounter the same issue and the explanation given above doesn't quite make it expected behaviour.

my configuration seems to be in line with the requirements:
```
  match_json_path = [
    "$.status",
  ]

  response_content_type = "J"
```

That is, expected response is json, json matcher is configured and no text matchers are configured.

Yet I see `Error: json: cannot unmarshal string into Go struct field RestApiMonitor.json_schema of type map[string]interface {}` and the apply passes (next apply is clean).

I believe the error should not be thrown at all if the configuration passes (and if the configuration is not right, the error message could be more helpful).
